project:
  type: book

book:
  title: "openMSE Technical Manual"
  author: "Adrian Hordyk, Quang Huynh, and Tom Carruthers"
  # cover-image: images/openMSE_logo.png
  description: |
    Management Strategy Evaluation with openMSE
  site-url: https://docs.openMSE.com/
  repo-url: https://github.com/blue-matter/openMSETechGuide/
  repo-actions: [edit]
  favicon: images/favicon.png
  date: today

  chapters:
    - index.qmd
    - part: OM_overview.qmd
      chapters:
        - OM_build.qmd
        # - importOM.qmd
        # - conditionOM.qmd
    - part: Eq_overview.qmd
      chapters:
        - Eq_popdynamics.qmd
  sidebar:
    title: 'Technical Manual'
    logo: "images/openMSE_logo.png"
    tools:
      - icon: globe
        href: https://openMSE.com
        text: "openMSE"
    search: true
    collapse-level: 1
format:
  html:
    theme: cosmo
    code-link: true


