project:
  type: book


book:
  title: "openMSE Technical Manual"
  author: "Adrian Hordyk, Quang Huynh, and Tom Carruthers"
  description: |
    Management Strategy Evaluation with openMSE
  favicon: images/favicon.png

  reader-mode: true
  site-url: https://docs.openMSE.com/
  repo-url: https://github.com/blue-matter/openMSETechGuide/
  repo-actions: [edit, issue]


  date: today

  chapters:
  - index.qmd

  - part: Management Strategy Evaluation
    chapters:
    - aboutMSE.Rmd
    - MSEroadmap.Rmd

  - part: About openMSE
    chapters:
    - intro.Rmd
    - prerequisites.Rmd
    - rPackages.Rmd
    - openMSE2.Rmd
    - MSEoverview.Rmd

  - part: Operating Models
    chapters:
    - operatingmodels.Rmd
    - importingOMs.Rmd

  - part: Stock Object
    chapters:
    - stockobject.Rmd
    - populatingstock.Rmd
    - plottingstock.qmd

  - part: Fleet Object
    chapters:
    - fleetobject.Rmd


  - part: Observation Object
    chapters:
    - obsobject.Rmd

  - part: Implementation Object
    chapters:
    - impobject.Rmd

  - part: Fishery Data
    chapters:
    - fisherydata.Rmd
    - dataobject.Rmd

  - part: Rapid Conditioning Model
    chapters:
    - RCM.Rmd

  - part: OM Case Studies
    chapters:
    - reeffish.Rmd
    - octopus.Rmd

  - part: Management Procedures
    chapters:
    - aboutMPs.Rmd
    - buildingMPs.Rmd
    - recobject.Rmd
    - builtinMPs.Rmd

  - part: Other Objects
    chapters:
    - histobject.Rmd
    - MSEobject.Rmd

  - part: Calculating Performance
    chapters:
    - performancemetric.Rmd
    - PMMethods.Rmd
    - slick.Rmd
    - plotstables.Rmd

  - part: Under the Hood
    chapters:
    - processoverview.Rmd
    - populate.Rmd


  - references.qmd

  appendices:
    - Acknowledgements.Rmd
    - authors.Rmd
    - bug-reports.Rmd

  sidebar:
    title: 'Technical Manual'
    logo: "images/OpenMSE2_color.png"
    pinned: true
    align: center
    tools:
      - icon: globe
        href: https://openMSE.com
        text: "openMSE"
    style: "docked"
    search: true
    collapse-level: 1

bibliography: references.bib
csl: fisheries-research.csl


format:
  html:
    theme: [cosmo, custom.scss]
    code-link: true
  asciidoc: default


