project:
  preview:
    port: 4200
    browser: true
  type: book
  output-dir: docs

book:
  title: "openMSE Technical Manual"
  author: "Adrian Hordyk, Quang Huynh, and Tom Carruthers"
  # cover-image: images/openMSE_logo.png
  description: |
    Management Strategy Evaluation with openMSE
  site-url: https://docs.openMSE.com/
  repo-url: https://github.com/blue-matter/openMSETechGuide/
  repo-actions: [edit]
  favicon: images/favicon.png
  date: today

  chapters:
    - index.qmd
    - openmse.qmd
    - getting_started.qmd
    - part: walkthrough.qmd
      chapters:
        - walkthrough_om_initialize.qmd
        - walkthough_build_stock.qmd
        - walkthough_build_fleet.qmd
        - walkthough_build_obs.qmd
        - walkthough_add_objects.qmd
        - walkthough_hist.qmd
        - walkthough_build_mps.qmd
        - walkthough_mse.qmd
    - part: operatingmodels.qmd
      chapters:
        - OM_condition.qmd
        - OM_import.qmd
        - OM_convert.qmd
    - part: OM_casestudies.qmd
      chapters:
        - OM_octopus.qmd
    - part: Eq_overview.qmd
      chapters:
        - Eq_popdynamics.qmd
  sidebar:
    title: 'Technical Manual'
    logo: "images/openMSE_logo.png"
    tools:
      - icon: globe
        href: https://openMSE.com
        text: "openMSE"
    search: true

format:
  html:
    theme: cosmo
    code-link: true

