project:
  type: book

book:
  title: "openMSE Technical Manual"
  author: "Adrian Hordyk, Quang Huynh, and Tom Carruthers"
  description: |
    Management Strategy Evaluation with openMSE
  favicon: images/favicon.png

  reader-mode: true
  site-url: https://docs.openMSE.com/
  repo-url: https://github.com/blue-matter/openMSETechGuide/
  repo-actions: [edit, issue]

  date: today

  chapters:
  - index.qmd
  - intro.Rmd
  - prerequisites.Rmd
  - rPackages.Rmd
  - openMSE2.Rmd


  - part: Operating Models
    chapters:
    - operatingmodels.Rmd

  - part: OM Case Studies
    chapters:
    - OMCaseStudies.Rmd
    - OctopusOM.Rmd

  - part: Management Procedures
    chapters:
    - MPs.Rmd
    - MPCaseStudies.Rmd

  - references.qmd

  appendices:
    - Acknowledgements.Rmd
    - authors.Rmd
    - bug-reports.Rmd

  sidebar:
    title: 'Technical Manual'
    logo: "images/OpenMSE2_color.png"
    pinned: true
    align: center
    tools:
      - icon: globe
        href: https://openMSE.com
        text: "openMSE"
    style: "docked"
    search: true
    collapse-level: 1

# bibliography: references.bib
# csl: fisheries-research.csl

collapse-level: 1

format:
  html:
    theme: [cosmo, custom.scss]
    code-link: true
  asciidoc: default


